### ISSUE TITLE
LocalStorage Checklist

### ISSUE THREAD

**Issue by MatthewBorabo** [Trystan-Schmits/MiniProject#1]

**Comment by Trystan-Schmits** [comment]
# [documentation](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage)

## Namely 4 major important functions:
- `localStorage.setItem(key,value)`
- `localStorage.getItem(key)`
- `localStorage.removeItem(key)`
- `localStorage.clear()`

**Comment by Trystan-Schmits** [comment]
Created a class for saving and loading from local storage called **LocalStorage**.
Created a class for navigation **Controller**. This class extends LocalStorage and handles saving *currentLevel* and  creating a table for the navigation.

[link to LocalStorage.js](https://github.com/Trystan-Schmits/MiniProject/blob/main/assets/js/platformer/LocalStorage.js)
[link to Controller.js](https://github.com/Trystan-Schmits/MiniProject/blob/main/assets/js/platformer/Controller.js)

examples of these files being used are in the active game.
